version: '3.9'

volumes:
  pgdata:

networks:
  backend:

services:
  website:
    build: .
    env_file:
      - smhenvsmh
    depends_on:
      - postgresql
    networks:
      - backend
    ports:
      - '5000':'5000'

  postgresql:
    image: 'postgres:12'
    env_file:
      - smhenvsmh
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend






