# примеры API-запросов

@baseUrl = http://localhost:5000

# создание объявления
POST {{baseUrl}}/advertisment
Content-Type: application/json

{
  "owner_id": 9,
  "title": "К0000000000",
  "description": "Н1000000000000",
  "created": "hit4fywysgti"
}

###

# получение объявления
GET {{baseUrl}}/advertisment/9
Content-Type: application/json

###

# обновление объявления
PATCH {{baseUrl}}/advertisment/9
Content-Type: application/json

{
  "description": "НЕ !!!Самые сочные и ароматные помидорки",
  "title": "ыыыыыыыы!"
}

###

# удаление объявление
DELETE {{baseUrl}}/advertisment/8
Content-Type: application/json

###

# создание пользователя
POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "NotIvan",
  "email": "iv11@nmail.ru",
  "password": "123456"
}

###

# получение пользователя
GET {{baseUrl}}/user/1
Content-Type: application/json

###

# обновление пользователя
PATCH {{baseUrl}}/user/1
Content-Type: application/json

{
  "name": "egor",
  "password": "12345Ac687",
  "email": "eg1ddor@bk.ru"
}

###

# удаление пользователя
DELETE {{baseUrl}}/user/3
Content-Type: application/json

###
